# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/fulls"

# UI configs
title: "אריאל ונתאי – צילום"
subtitle: "תיקיית תמונות לדוגמה"
author: "אריאל ונתאי"
header:
 title: "אריאל ונתאי"
 subtitle: "תיקיית תמונות לדוגמה"